import fs from 'node:fs/promises';
import path from 'node:path';
import { installVoice, inspectVoiceSource } from '../runtime/kokoro/install.mjs';
const args = process.argv.slice(2);
const arg = name => { const i = args.indexOf(name); return i >= 0 ? args[i + 1] : undefined; };
const target = `${process.platform}-${process.arch}`;
if (args.includes('--windows') && target !== 'win32-x64') throw new Error('请在 Windows x64 准备声音运行时');
const source = arg('--from');
if (!source) throw new Error('Usage: node scripts/prepare-kokoro.mjs --from <model or bundle directory> [--python <independent Python>]');
const exists = async file => fs.access(file).then(() => true, () => false);
const isTingye = await exists(path.join(source, 'macos_dev/kokoro_worker.py'));
const modelDirectory = isTingye ? path.join(source, 'models/kokoro-int8-multi-lang-v1_1') : await exists(path.join(source, 'model')) ? path.join(source, 'model') : source;
const pythonDirectory = arg('--python') || (isTingye ? path.join(source, target === 'win32-x64' ? 'build/windows-package/听页/Kokoro/python' : '.runtime/mac-portable/python') : path.join(source, 'python'));
const inspected = await inspectVoiceSource(modelDirectory);
const bundle = path.resolve('runtime/kokoro/bundle', target);
await installVoice({ destination: bundle, directory: modelDirectory, pythonDirectory, modelId: inspected.modelId || 'kokoro-v1.1-int8' });
await fs.mkdir('runtime/kokoro/manifests', { recursive: true });
await fs.copyFile(path.join(bundle, 'manifest.json'), path.join('runtime/kokoro/manifests', `${target}.json`));
console.log(`Kokoro ONNX Runtime ready: ${bundle}`);
